# Generated by Django 4.2 on 2023-11-29 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserDeviceLimit',
            new_name='CustomerDeviceLimit',
        ),
    ]
