# Generated by Django 4.2 on 2023-11-29 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_userdevicelimit_customerdevicelimit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='customerdevicelimit',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='customernetworksetting',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='CustomerDeviceLimit',
        ),
        migrations.DeleteModel(
            name='CustomerNetworkSetting',
        ),
    ]
