# Generated by Django 4.2.17 on 2024-12-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenAIAPIUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(help_text="The OpenAI endpoint used, e.g., 'text-davinci-003'.", max_length=255)),
                ('total_tokens', models.IntegerField(help_text='Total tokens used for the API request.')),
                ('prompt_tokens', models.IntegerField(help_text='Prompt token used for the API request.')),
                ('completion_tokens', models.IntegerField(help_text='Completion tokens generated for the API request.')),
                ('request_timestamp', models.DateTimeField(auto_now_add=True, help_text='The timestamp when the API request was made.')),
                ('response_time', models.FloatField(blank=True, help_text='Response time in seconds, if tracked.', null=True)),
            ],
            options={
                'verbose_name': 'OpenAI API Usage',
                'verbose_name_plural': 'OpenAI API Usages',
                'ordering': ['-request_timestamp'],
            },
        ),
    ]
