# Generated by Django 4.2 on 2024-02-14 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_id', models.CharField(blank=True, max_length=255, null=True)),
                ('myob_uid', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('myob_row_version', models.BigIntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, default='No description is provided.', null=True)),
                ('status', models.CharField(blank=True, choices=[('NI', 'Not Initiated'), ('PN', 'Pending'), ('CP', 'Complete'), ('IA', 'Immediate Action')], default='NI', max_length=2)),
                ('is_active', models.BooleanField(default=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('finish_date', models.DateTimeField(blank=True, null=True)),
                ('last_modified_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('uri', models.URLField(blank=True, null=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.address')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.customer')),
                ('parent_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job_management.job')),
            ],
        ),
    ]
