# Generated by Django 4.2 on 2024-02-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(blank=True, choices=[('Not Initiated', 'Not Initiated'), ('Pending', 'Pending'), ('Complete', 'Complete'), ('Immediate Action', 'Immediate Action')], default='Not Initiated', max_length=20),
        ),
    ]
