# Generated by Django 4.2 on 2024-02-15 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_management', '0004_alter_assignment_roster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, help_text='Enter the check description here.', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CheckList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('checks', models.ManyToManyField(to='job_management.check')),
            ],
        ),
    ]
