# Generated by Django 4.2 on 2024-02-15 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_management', '0005_check_checklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='checklist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='job_management.checklist'),
        ),
    ]
