# Generated by Django 4.2.17 on 2024-12-05 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_management', '0006_job_checklist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ('-created_at',)},
        ),
    ]
