# Generated by Django 4.2.17 on 2024-12-05 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Criteria Name')),
                ('key', models.CharField(max_length=255, verbose_name='Criteria Key')),
                ('type', models.CharField(choices=[('equals', 'Equals'), ('less_than', 'Less Than'), ('greater_than', 'Greater Than'), ('not', 'Not')], max_length=20, verbose_name='Type')),
                ('value', models.CharField(max_length=255, verbose_name='Value')),
                ('is_required', models.BooleanField(default=False, verbose_name='Is Required')),
            ],
            options={
                'verbose_name': 'Criteria',
                'verbose_name_plural': 'Criterias',
            },
        ),
        migrations.CreateModel(
            name='SourceWebsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Website Name')),
                ('logo', models.ImageField(upload_to='website_logos/', verbose_name='Website Logo')),
                ('script_name', models.CharField(max_length=255, verbose_name='Scraper Script Name')),
                ('url', models.URLField(max_length=255, verbose_name='Website URL')),
            ],
            options={
                'verbose_name': 'Source Website',
                'verbose_name_plural': 'Source Websites',
            },
        ),
        migrations.CreateModel(
            name='ScrapingProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_query', models.CharField(max_length=255, verbose_name='Search Query')),
                ('max_records', models.PositiveIntegerField(default=0, verbose_name='Max Records')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Status')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Started At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('criterias', models.ManyToManyField(to='scraper.criteria', verbose_name='Criterias')),
                ('source_websites', models.ManyToManyField(to='scraper.sourcewebsite', verbose_name='Source Websites')),
                ('started_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Started By')),
            ],
            options={
                'verbose_name': 'Scraping Process',
                'verbose_name_plural': 'Scraping Processes',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Product Title')),
                ('category', models.CharField(blank=True, max_length=255, null=True, verbose_name='Category')),
                ('description', models.TextField(verbose_name='Description')),
                ('thumbnail', models.ImageField(upload_to='product_thumbnails/', verbose_name='Thumbnail')),
                ('is_published', models.BooleanField(default=False, verbose_name='Is Published')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20, verbose_name='Status')),
                ('page_screenshot', models.ImageField(upload_to='page_screenshots/', verbose_name='Page Screenshot')),
                ('is_commercial_allowed', models.BooleanField(default=False, verbose_name='Is Commercial Allowed')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('scraped_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.scrapingprocess', verbose_name='Scraped By')),
                ('source_website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.sourcewebsite', verbose_name='Source Website')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Image Name')),
                ('image_file', models.ImageField(upload_to='product_images/', verbose_name='Image File')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='scraper.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
    ]
