# Generated by Django 4.2.17 on 2024-12-09 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_license_pagescreenshot_product_sku_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapingprocess',
            name='criterias',
            field=models.ManyToManyField(blank=True, null=True, to='scraper.criteria', verbose_name='Criterias'),
        ),
    ]
