# Generated by Django 4.2.17 on 2024-12-09 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_remove_image_name_image_image_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThumbnailImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='thumbnail_images/', verbose_name='Thumbnail Image')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Thumbnail URL')),
            ],
            options={
                'verbose_name': 'Thumbnail Image',
                'verbose_name_plural': 'Thumbnail Images',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='thumbnail',
        ),
    ]
