# Generated by Django 4.2.17 on 2024-12-12 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0007_alter_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('under_review', 'Under Review'), ('declined', 'Declined'), ('approved', 'Approved'), ('published', 'Published'), ('archived', 'Archived')], default='under_review', max_length=20, verbose_name='Status'),
        ),
    ]
