# Generated by Django 4.2.17 on 2024-12-18 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0009_alter_product_options_product_publishing_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-created_at', '-updated_at'), 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
