# Generated by Django 4.2.17 on 2025-01-11 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0010_alter_product_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagescreenshot',
            name='image',
        ),
        migrations.AddField(
            model_name='pagescreenshot',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='page-screenshot'),
        ),
    ]
