# Generated by Django 4.2.17 on 2025-01-11 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0011_remove_pagescreenshot_image_pagescreenshot_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=1000, verbose_name='Product Title'),
        ),
    ]
