# Generated by Django 4.2.17 on 2025-01-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0012_alter_product_category_alter_product_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='model_id',
            field=models.IntegerField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='model_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
