# Generated by Django 4.2.17 on 2025-01-11 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0013_product_model_id_product_model_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='wocommerce_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
