# Generated by Django 4.2.17 on 2025-01-12 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0014_product_wocommerce_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='author_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
