# Generated by Django 4.2.17 on 2025-01-16 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0015_product_author_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcewebsite',
            name='script_name',
            field=models.CharField(max_length=255, verbose_name='Script Name'),
        ),
    ]
